# week08/k8s/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: ecomm-secrets-w10
type: Opaque # Indicates arbitrary user-defined data
data:
  # PostgreSQL Credentials (for both Product DB and Order DB)
  POSTGRES_USER: "cG9zdGdyZXM=" # Base64 for 'postgres'
  POSTGRES_PASSWORD: "cG9zdGdyZXM=" # Base64 for 'postgres'

  # Azure Storage Account Credentials for Product Service image uploads
  # REPLACE WITH YOUR ACTUAL BASE64 ENCODED VALUES from your Azure Storage Account
  # Example: echo -n 'myblobstorageaccount' | base64
  AZURE_STORAGE_ACCOUNT_NAME: "d2VlazEwc3RvcmFnZWFjY3Q="
  # Example: echo -n 'your_storage_account_key_string' | base64
  AZURE_STORAGE_ACCOUNT_KEY: "U1NSTG1LdUVpbUd6KzlHSXF4UG5uRmV0L0E1OTk2aFBsVklLUWpCMjhnVENtZUU4bmV4TVViRzR0MlpZdDBCeTU2RXR5MWNIRGdrZCtBU3RxTEtpOUE9PQ=="
