name: Frontend CD - Push to main with Backend IPs

on:
  workflow_run:
    workflows: ["Frontend CD - Deploy to AKS with external IPS"]
    types:
      - completed

  workflow_dispatch:


jobs:
  push_to_main:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: development   # Checkout the development branch

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge development into main
        run: |
          git fetch origin main
          git checkout main
          git merge --no-ff development -m "Merge development into main [CI/CD]" || echo "Nothing to merge"

      - name: Push changes to main
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main