name: Frontend CD - Deploy to AKS with external IPS

on:
  workflow_dispatch:
    inputs:
      product_api_ip:
        description: 'Product Service External IP'
        required: true
      order_api_ip:
        description: 'Order Service External IP'
        required: true
      customer_api_ip:
        description: 'Customer Service External IP'
        required: true
      aks_cluster_name:
        description: 'AKS Cluster Name'
        required: true
      aks_resource_group:
        description: 'Resource Group Name'
        required: true

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    environment: Production

    env:
      IMAGE_TAG: ${{ github.sha }}
      ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker Login to ACR
        run: az acr login --name $ACR_NAME

      - name: Inject Backend IPs into Frontend main.js
        run: |
          sed -i "s|_PRODUCT_API_URL_|${{ inputs.product_api_ip }}|g" frontend/main.js
          sed -i "s|_ORDER_API_URL_|
