name: Frontend CD - Deploy to AKS with external IPS
on:
  workflow_run:
    workflows: ["Backend/Frontend CD - Deploy to AKS (Development)"]

    types: [completed]

  workflow_dispatch:

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    environment: Production

    env:
      IMAGE_TAG: ${{ github.sha }}
      ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker Login to ACR
        run: az acr login --name $ACR_NAME

      - name: Build & Push Frontend Image
        run: |
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/frontend:latest ./frontend/
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/frontend:latest

      - name: Set Kubernetes context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Deploy Frontend
        run: kubectl apply -f k8s/frontend.yaml

      - name: Logout from Azure
        if: always()
        run: az logout
